spring:
  application.name: sample-layered-simple-crud
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DEMO_POSTGRESQL_URL}
    username: ${DEMO_POSTGRESQL_USERNAME}
    password: ${DEMO_POSTGRESQL_PASSWORD}

    # connection pool (usage: hikari pool)
    hikari:
      connection-timeout: 30_000
      idle-timeout: 60_000
      max-lifetime: 1_800_000
      maximum-pool-size: 300
      minimum-idle: 5
      leak-detection-threshold: 2000

  jpa:
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # profile ?? ? ?? ??? ? ??? ??? true ?.
    hibernate:
      ddl-auto: none # flyway ???? none ?? validate (??? ?? validate)

  flyway:
    baseline-on-migrate: true # flyway schema history ???? ??? ????.
    locations:
      - classpath:db/migration/v1_0